# version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  redis:
    image: redis:latest
    container_name: teamclash-redis
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./backend
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./UploadedFiles:/app/UploadedFiles

